name: Check Links on PR
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
permissions: write-all
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: lycheeverse/lychee-action@v1
        with:
          fail: false
          format: markdown
          jobSummary: true
          output: ./lychee/results.md
          args: --base . --verbose --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
      - name: Comment Broken Links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./lychee/results.md
  