name: Check Links on PR
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions: write-all
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          format: markdown
          jobSummary: true
          output: ./lychee/results.md
          args: --base . --verbose --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  