#
# GitHub Actions Workflow for pull request events against the main branch to
# make sure Jekyll still builds. If successful, the resulting html files are
# uploaded as artifacts to make it easier to preview the results of a PR.
#
# For more information on the actions used in this workflow, please see:
#   https://github.com/actions/checkout
#   https://github.com/marketplace/actions/build-jekyll
#   https://github.com/actions/upload-artifact
#
name: Check Jekyll Build
on:
  pull_request:
    branches: [ main ]

jobs:
  # Job to test that web pages build
  jekyll_build:
    name: Jekyll build of web pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Jekyll
        uses: nigelbritton/jekyll-build-action@v1.1

      - name: Upload CF Website artifact
        uses: actions/upload-artifact@v4
        with:
          name: CF Website
          path: ./_site/
          
